# -*- coding: utf-8 -*-

# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1500, 1000)

        self.one = QtWidgets.QWidget(Form)
        self.one.setGeometry(QtCore.QRect(100, 200, 300, 200))
        self.one.setStyleSheet("background-color: rgb(6, 123, 194);")
        self.one.setObjectName("one")

        self.two = QtWidgets.QWidget(Form)
        self.two.setGeometry(QtCore.QRect(1000, 100, 400, 400))
        self.two.setStyleSheet("background-color: rgb(132, 188, 218);")
        self.two.setObjectName("two")

        self.three = QtWidgets.QWidget(Form)
        self.three.setGeometry(QtCore.QRect(500, 200, 300, 500))
        self.three.setStyleSheet("background-color: rgb(236, 195, 11);")
        self.three.setObjectName("three")

        self.four = QtWidgets.QWidget(Form)
        self.four.setGeometry(QtCore.QRect(200, 600, 400, 300))
        self.four.setStyleSheet("background-color: rgb(243, 119, 72);")
        self.four.setObjectName("four")

        self.five = QtWidgets.QWidget(Form)
        self.five.setGeometry(QtCore.QRect(900, 800, 400, 100))
        self.five.setStyleSheet("background-color: rgb(213, 96, 98);")
        self.five.setObjectName("five")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Sticky"))

    def resetUi(self, Form):
        for i in reversed(range(Form.count())):
            widgetToRemove = Form.itemAt(i).widget()
            Form.removeWidget(widgetToRemove)
            widgetToRemove.setParent(None)

        self.one = QtWidgets.QWidget(Form)
        self.one.setGeometry(QtCore.QRect(100, 200, 300, 200))
        self.one.setStyleSheet("background-color: rgb(6, 123, 194);")
        self.one.setObjectName("one")

        self.two = QtWidgets.QWidget(Form)
        self.two.setGeometry(QtCore.QRect(1000, 100, 400, 400))
        self.two.setStyleSheet("background-color: rgb(132, 188, 218);")
        self.two.setObjectName("two")

        self.three = QtWidgets.QWidget(Form)
        self.three.setGeometry(QtCore.QRect(500, 200, 300, 500))
        self.three.setStyleSheet("background-color: rgb(236, 195, 11);")
        self.three.setObjectName("three")

        self.four = QtWidgets.QWidget(Form)
        self.four.setGeometry(QtCore.QRect(200, 600, 400, 300))
        self.four.setStyleSheet("background-color: rgb(243, 119, 72);")
        self.four.setObjectName("four")

        self.five = QtWidgets.QWidget(Form)
        self.five.setGeometry(QtCore.QRect(900, 800, 400, 100))
        self.five.setStyleSheet("background-color: rgb(213, 96, 98);")
        self.five.setObjectName("five")

